### ISSUE TITLE
Unnecessary use of "self"

### ISSUE THREAD

**Issue by YeldhamDev** [coppolaemilio/gamemaker-godot-dictionary#6]
First, thank you for creating this. It's a handy tool for people coming from GM.

Anyways, I noticed that in the code examples, the `self` keyword is used a lot, when there's no need for it. For example: `self.queue_free()` where it could just be `queue_free()`.

**Comment by coppolaemilio** [comment]
That is true! It is mostly because of people like me coming from a python background as well. Some PTSD of writing self. on everything. I'll see what the code guidelines are for GDScript and update accordingly! Thanks for your comment :)

**Comment by YeldhamDev** [comment]
You can find them here: https://docs.godotengine.org/en/3.1/getting_started/scripting/gdscript/gdscript_styleguide.html
