### ISSUE TITLE
ColorN(color) Alternative Suggestion

### ISSUE THREAD

**Issue by NoodleSushi** [coppolaemilio/gamemaker-godot-dictionary#9]
Instead of `ColorN("red")`, you could use the `Color` constants and go for `Color.red` instead.

**Comment by coppolaemilio** [comment]
yeah, that seems like a much better solution! I haven't been updating this guide because I feel like GDScript is so much fresher than GML than I completely forget about it hahaha, I'll see if I can make the edits soon. Otherwise feel free to make a commit and I'll review/push it :)
